name: 'Simple Action'
description: 'A simple GitHub Action example'
inputs:
  message:
    description: 'The message to print'
    required: true
    default: 'Hello from the action!'
runs:
  using: 'node12'
  main: 'index.js'
