name: haGfhyegbdhybgfySHBEGUYgdeYASIYGHwrehbiAUR
description: eaigfysreuvgfbosiubgdeipueasHBPIGUSEgf
inputs:
  demo:
    required: true
    type: string
runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.demo }}
