name: abcd
on:
    push: 
jobs:
    abcdef:
        runs-on: ubuntu-latest
        name: avc
        steps:
        - uses: actions/checkout@v4
        - run: ls -lrth
        - uses: actions/setup-node@v4
        - run: npm install
        - run: ls -larth ./js/
        - name: kkk
          uses: ./js/
          with:
            message: "asif first"
        